PyObject *SetupException;

void define_exceptions(PyObject *module);

